version: '3.3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_USER=tunt
      - MYSQL_PASSWORD=120597
      - MYSQL_ROOT_PASSWORD=12051997
      - MYSQL_DATABASE=talatuda
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=12051997
    ports:
      - 12331:80
  api:
    image: tontumo12/tunt:api
    container_name: tunt_api
    restart: always
    build:
      context: ../api
      dockerfile: ../.docker/api/Dockerfile
    ports:
      - "12332:3000"
    depends_on:
      - db
  web:
    image: tontumo12/tunt:vue
    container_name: tunt_web
    build:
      context: ../web
      dockerfile: ../.docker/web/Dockerfile
    ports:
      - 12333:8080