version: '3.3'
services:
  mysql:
    image: tontumo12/tunt:mysql
    container_name: tunt_db
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - "12345:12345"
  api:
    image: tontumo12/tunt:api
    container_name: tunt_api
    build:
      context: ../api
      dockerfile: ../.docker/api/Dockerfile
    ports:
      - "12332:3000"
  web:
    image: tontumo12/tunt:web
    container_name: tunt_web
    build:
      context: ../web
      dockerfile: ../.docker/web/Dockerfile
    ports:
      - "12333:8080"
    depends_on:
      - mysql